sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9iLp94i9HAET34wZbX
    access-key-secret: eiuPcsSIto3ruzIkzYBwFw0aazLasV
    bucket-name: sky-take-out1234561
